name: Delete Recipe returns 404 for invalid recipe ID
modules:
  - http = http
  - recipeHelpers
steps:
  - apiKey = getApiKey

  - result = http.delete:
      url: $recipeUrl/recipes/$_id()
      headers:
          Authorization: $apiKey
  - http.isNotFound: $result
  - areEqual:
      expected: Recipe does not exist
      actual: $result.body